IDENTIFICATION DIVISION.
PROGRAM-ID. SendPacket-KnownPacks.

DATA DIVISION.
WORKING-STORAGE SECTION.
    01 PACKET-ID        BINARY-LONG             VALUE H'0E'.
    *> buffer used to store the packet data
    01 PAYLOAD          PIC X(1024).
    01 PAYLOADPOS       BINARY-LONG UNSIGNED.
    01 PAYLOADLEN       BINARY-LONG UNSIGNED.
    *> temporary
    01 INT32            BINARY-LONG.
LINKAGE SECTION.
    01 LK-CLIENT        BINARY-LONG UNSIGNED.

PROCEDURE DIVISION USING LK-CLIENT.
    MOVE 1 TO PAYLOADPOS

    *> count
    MOVE 1 TO INT32
    CALL "Encode-VarInt" USING INT32 PAYLOAD PAYLOADPOS

    *> pack namespace
    MOVE FUNCTION CHAR(9 + 1) TO PAYLOAD(PAYLOADPOS:1)
    ADD 1 TO PAYLOADPOS
    MOVE "minecraft" TO PAYLOAD(PAYLOADPOS:9)
    ADD 9 TO PAYLOADPOS

    *> pack id
    MOVE FUNCTION CHAR(4 + 1) TO PAYLOAD(PAYLOADPOS:1)
    ADD 1 TO PAYLOADPOS
    MOVE "core" TO PAYLOAD(PAYLOADPOS:4)
    ADD 4 TO PAYLOADPOS

    *> pack version
    MOVE FUNCTION CHAR(6 + 1) TO PAYLOAD(PAYLOADPOS:1)
    ADD 1 TO PAYLOADPOS
    MOVE "1.20.6" TO PAYLOAD(PAYLOADPOS:6)
    ADD 6 TO PAYLOADPOS

    *> send packet
    COMPUTE PAYLOADLEN = PAYLOADPOS - 1
    CALL "SendPacket" USING LK-CLIENT PACKET-ID PAYLOAD PAYLOADLEN
    GOBACK.

END PROGRAM SendPacket-KnownPacks.
